max_width = 100
use_small_heuristics = "Max"

attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 0           #35
array_width = 60
chain_width = 80                   #60
single_line_if_else_max_width = 50

wrap_comments = true
comment_width = 120

imports_granularity = "Module"
match_arm_blocks = true

# imports_layout = "Horizontal"
#format_strings = true
