[package]
name = "mtorrent-core"
description = "Deprecated: renamed to mtorrent-base"
categories = ["asynchronous", "network-programming", "parser-implementations"]
keywords = ["bittorrent", "torrent", "protocol", "tracker", "p2p"]
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
mocks = ["mtorrent-base/mocks"]

[dependencies]
mtorrent-base = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
