name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: ./cargo.sh build --release --all-targets --verbose
    - name: Run tests
      run: ./cargo.sh nextest run --all-targets --all-features
    - name: Lint
      run: ./cargo.sh clippy --all-targets --all-features -- -D warnings
    - name: Check formatting
      run: ./cargo.sh fmt --check --verbose
