name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.80.0
        profile: minimal
        override: true
        components: rustfmt, clippy
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Install nextest
      uses: actions-rs/cargo@v1
      with:
        command: binstall
        args:  cargo-nextest --secure -y
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-targets --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run --all-targets --all-features
    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings
    - name: Lint release
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --release --all-targets --all-features -- -D warnings
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check --verbose
